name: "Update Configuration and Build"

on:
  workflow_dispatch:
  push:

jobs:
  update:
    name: "Update Configuration & Build"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: |
          deno task bundle
        shell: bash
#      - uses: ubiquity-os/action-deploy-plugin@main
#        with:
#          treatAsEsm: true
#          sourcemap: false
#        env:
#          APP_ID: ${{ secrets.APP_ID }}
#          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
